### PR TITLE
[NoMerge] Patch gaia6 to support ordered transfer channel

### PR DESCRIPTION
**Pull request by soareschen**
This is for testing https://github.com/informalsystems/ibc-rs/issues/1835.

### CODE REVIEW

**Comment by soareschen** [comment]
@JonathanLorimer it seems like no matter what `replace` directive is used, it is always ignored by the Nix go builder. This is probably the same bug as https://github.com/tweag/gomod2nix/issues/26.

**Comment by JonathanLorimer** [comment]
I wonder if the issue is [here](https://github.com/tweag/gomod2nix/blob/master/builder/parser.nix#L97-L114)

**Comment by soareschen** [comment]
@JonathanLorimer it seems like the quirk is probably in the Go code for `gomod2nix`. I tried editing `go-modules.toml` manually in ea7f02fee8c525f29ccd2fa2fcebffce7e0b952c, and my patch is now working.

**Comment by soareschen** [comment]
Turns out the fix is rather simple: https://github.com/tweag/gomod2nix/pull/30

**Comment by JonathanLorimer** [comment]
closing due to #64

**Pull request closed without merging**
