### PR TITLE
Add ldflags to gaia

### LINKED ISSUE #53: `gaiad` binary built from Nix do not contain version information
The original `gaia` build script contains some magic in the [Makefile](https://github.com/cosmos/gaia/blob/v4.2.1/Makefile#L64-L69) that injects version info to the code before compilation.

Other than that, the information about build dependencies is retried using [`debug.ReadBuildInfo()`](https://github.com/cosmos/cosmos-sdk/blob/v0.44.3/version/version.go#L89-L90), which is apparently only [available only in binaries built with module support](https://pkg.go.dev/runtime/debug#ReadBuildInfo) and is missing in the Nix build.

Without these information, the GRPC query to the gaiad version info only return empty strings and empty arrays. This impacts the ability for clients such as Hermes to determine the version of the Gaia full node it is communicating to.

### PR DESCRIPTION
**Pull request by JonathanLorimer**
Closes #53

### CODE REVIEW

**Comment by soareschen** [comment]
Awesome! Thanks for finding out the use of `buildFlagsArray` in `buildGoApplication`. This partially fixes the problems in #53, although `debug.ReadBuildInfo()` is still currently not working.

The [documentation](https://pkg.go.dev/runtime/debug#ReadBuildInfo) says that "the information is available only in binaries built with module support", but it is unclear what does it meant by module support being enabled. I only found out about `GO111MODULE`, but that seems to already been enabled by `buildGoApplication`, so there are probably some other magic going on.

In any case we can merge this first and then figure out how to enable the module support in Nix.

FYI this is the version info output by gaiad in Nix:

```
{ name: "gaia", app_name: "gaiad", version: "4.2.1", git_commit: "dbd8a6fb522c571debf958837f9113c56d418f6b", build_tags: "", go_version: "go version go1.16.6 linux/amd64", build_deps: [Module { path: "", version: "(devel)", sum: "" }], cosmos_sdk_version: "" }
```

And this is the version info output by gaiad built from `make`:

```
{ name: "gaia", app_name: "gaiad", version: "v4.2.1", git_commit: "dbd8a6fb522c571debf958837f9113c56d418f6b", build_tags: "netgo,ledger", go_version: "go version go1.16.7 linux/amd64", build_deps: [Module { path: "github.com/99designs/keyring", version: "v1.1.6", sum: "h1:kVDC2uCgVwecxCk+9zoCt2uEL6dt+dfVzMvGgnVcIuM=" }, Module { path: "github.com/ChainSafe/go-schnorrkel", version: "v0.0.0-20200405005733-88cbf1b4c40d", sum: "h1:nalkkPQcITbvhmL4+C4cKA87NW0tfm3Kl9VXRoPywFg=" }, Module { path: "github.com/Workiva/go-datastructures", version: "v1.0.52", sum: "h1:PLSK6pwn8mYdaoaCZEMsXBpBotr4HHn9abU0yMQt0NI=" }, Module { path: "github.com/armon/go-metrics", version: "v0.3.6", sum: "h1:x/tmtOF9cDBoXH7XoAGOz2qqm1DknFD1590XmD/DUJ8=" }, Module { path: "github.com/beorn7/perks", version: "v1.0.1", sum: "h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=" }, Module { path: "github.com/bgentry/speakeasy", version: "v0.1.0", sum: "h1:ByYyxL9InA1OWqxJqqp2A5pYHUrCiAL6K3J+LKSsQkY=" }, Module { path: "github.com/btcsuite/btcd", version: "v0.21.0-beta", sum: "h1:At9hIZdJW0s9E/fAz28nrz6AmcNlSVucCH796ZteX1M=" }, Module { path: "github.com/cespare/xxhash/v2", version: "v2.1.1", sum: "h1:6MnRN8NT7+YBpUIWxHtefFZOKTAPgGjpQSxqLNn0+qY=" }, Module { path: "github.com/confio/ics23/go", version: "v0.6.3", sum: "h1:PuGK2V1NJWZ8sSkNDq91jgT/cahFEW9RGp4Y5jxulf0=" }, Module { path: "github.com/cosmos/cosmos-sdk", version: "v0.42.4", sum: "h1:yaD4PyOx0LnyfiWasC5egg1U76lT83GRxjJjupPo7Gk=" }, Module { path: "github.com/cosmos/go-bip39", version: "v1.0.0", sum: "h1:pcomnQdrdH22njcAatO0yWojsUnCO3y2tNoV1cb6hHY=" }, Module { path: "github.com/cosmos/iavl", version: "v0.15.3", sum: "h1:xE9r6HW8GeKeoYJN4zefpljZ1oukVScP/7M8oj6SUts=" }, Module { path: "github.com/cosmos/ledger-cosmos-go", version: "v0.11.1", sum: "h1:9JIYsGnXP613pb2vPjFeMMjBI5lEDsEaF6oYorTy6J4=" }, Module { path: "github.com/cosmos/ledger-go", version: "v0.9.2", sum: "h1:Nnao/dLwaVTk1Q5U9THldpUMMXU94BOTWPddSmVB6pI=" }, Module { path: "github.com/davecgh/go-spew", version: "v1.1.1", sum: "h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=" }, Module { path: "github.com/dvsekhvalnov/jose2go", version: "v0.0.0-20200901110807-248326c1351b", sum: "h1:HBah4D48ypg3J7Np4N+HY/ZR76fx3HEUGxDU6Uk39oQ=" }, Module { path: "github.com/enigmampc/btcutil", version: "v1.0.3-0.20200723161021-e2fb6adb2a25", sum: "h1:2vLKys4RBU4pn2T/hjXMbvwTr1Cvy5THHrQkbeY9HRk=" }, Module { path: "github.com/felixge/httpsnoop", version: "v1.0.1", sum: "h1:lvB5Jl89CsZtGIWuTcDM1E/vkVs49/Ml7JJe07l8SPQ=" }, Module { path: "github.com/fsnotify/fsnotify", version: "v1.4.9", sum: "h1:hsms1Qyu0jgnwNXIxa+/V/PDsU6CfLf6CNO8H7IWoS4=" }, Module { path: "github.com/go-kit/kit", version: "v0.10.0", sum: "h1:dXFJfIHVvUcpSgDOV+Ne6t7jXri8Tfv2uOLHUZ2XNuo=" }, Module { path: "github.com/go-logfmt/logfmt", version: "v0.5.0", sum: "h1:TrB8swr/68K7m9CcGut2g3UOihhbcbiMAYiuTXdEih4=" }, Module { path: "github.com/godbus/dbus", version: "v0.0.0-20190726142602-4481cbc300e2", sum: "h1:ZpnhV/YsD2/4cESfV5+Hoeu/iUR3ruzNvZ+yQfO03a0=" }, Module { path: "github.com/gogo/gateway", version: "v1.1.0", sum: "h1:u0SuhL9+Il+UbjM9VIE3ntfRujKbvVpFvNB4HbjeVQ0=" }, Module { path: "github.com/gogo/protobuf", version: "v1.3.3", sum: "" }, Module { path: "github.com/golang/protobuf", version: "v1.4.3", sum: "h1:JjCZWpVbqXDqFVmTfYWEVTMIYrL/NPdPSCHPJ0T/raM=" }, Module { path: "github.com/golang/snappy", version: "v0.0.2", sum: "h1:aeE13tS0IiQgFjYdoL8qN3K1N2bXXtI6Vi51/y7BpMw=" }, Module { path: "github.com/google/btree", version: "v1.0.0", sum: "h1:0udJVsspx3VBr5FwtLhQQtuAsVc79tTq0ocGIPAU6qo=" }, Module { path: "github.com/google/orderedcode", version: "v0.0.1", sum: "h1:UzfcAexk9Vhv8+9pNOgRu41f16lHq725vPwnSeiG/Us=" }, Module { path: "github.com/gorilla/handlers", version: "v1.5.1", sum: "h1:9lRY6j8DEeeBT10CvO9hGW0gmky0BprnvDI5vfhUHH4=" }, Module { path: "github.com/gorilla/mux", version: "v1.8.0", sum: "h1:i40aqfkR1h2SlN9hojwV5ZA91wcXFOvkdNIeFDP5koI=" }, Module { path: "github.com/gorilla/websocket", version: "v1.4.2", sum: "h1:+/TMaTYc4QFitKJxsQ7Yye35DkWvkdLcvGKqM+x0Ufc=" }, Module { path: "github.com/grpc-ecosystem/go-grpc-middleware", version: "v1.2.2", sum: "h1:FlFbCRLd5Jr4iYXZufAvgWN6Ao0JrI5chLINnUXDDr0=" }, Module { path: "github.com/grpc-ecosystem/grpc-gateway", version: "v1.16.0", sum: "h1:gmcG1KaJ57LophUzW0Hy8NmPhnMZb4M0+kPpLofRdBo=" }, Module { path: "github.com/gsterjov/go-libsecret", version: "v0.0.0-20161001094733-a6f4afe4910c", sum: "h1:6rhixN/i8ZofjG1Y75iExal34USq5p+wiN1tpie8IrU=" }, Module { path: "github.com/gtank/merlin", version: "v0.1.1", sum: "h1:eQ90iG7K9pOhtereWsmyRJ6RAwcP4tHTDBHXNg+u5is=" }, Module { path: "github.com/gtank/ristretto255", version: "v0.1.2", sum: "h1:JEqUCPA1NvLq5DwYtuzigd7ss8fwbYay9fi4/5uMzcc=" }, Module { path: "github.com/hashicorp/go-immutable-radix", version: "v1.0.0", sum: "h1:AKDB1HM5PWEA7i4nhcpwOrO2byshxBjXVn/J/3+z5/0=" }, Module { path: "github.com/hashicorp/golang-lru", version: "v0.5.4", sum: "h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=" }, Module { path: "github.com/hashicorp/hcl", version: "v1.0.0", sum: "h1:0Anlzjpi4vEasTeNFn2mLJgTSwt0+6sfsiTG8qcWGx4=" }, Module { path: "github.com/libp2p/go-buffer-pool", version: "v0.0.2", sum: "h1:QNK2iAFa8gjAe1SPz6mHSMuCcjs+X1wlHzeOSqcmlfs=" }, Module { path: "github.com/magiconair/properties", version: "v1.8.4", sum: "h1:8KGKTcQQGm0Kv7vEbKFErAoAOFyyacLStRtQSeYtvkY=" }, Module { path: "github.com/mattn/go-isatty", version: "v0.0.12", sum: "h1:wuysRhFDzyxgEmMf5xjvJ2M9dZoWAXNNr5LSBS7uHXY=" }, Module { path: "github.com/matttproud/golang_protobuf_extensions", version: "v1.0.1", sum: "h1:4hp9jkHxhMHkqkrB3Ix0jegS5sx/RkqARlsWZ6pIwiU=" }, Module { path: "github.com/mimoo/StrobeGo", version: "v0.0.0-20181016162300-f8f6d4d2b643", sum: "h1:hLDRPB66XQT/8+wG9WsDpiCvZf1yKO7sz7scAjSlBa0=" }, Module { path: "github.com/minio/highwayhash", version: "v1.0.1", sum: "h1:dZ6IIu8Z14VlC0VpfKofAhCy74wu/Qb5gcn52yWoz/0=" }, Module { path: "github.com/mitchellh/go-homedir", version: "v1.1.0", sum: "h1:lukF9ziXFxDFPkA1vsr5zpc1XuPDn/wFntq5mG+4E0Y=" }, Module { path: "github.com/mitchellh/mapstructure", version: "v1.1.2", sum: "h1:fmNYVwqnSfB9mZU6OS2O6GsXM+wcskZDuKQzvN1EDeE=" }, Module { path: "github.com/mtibben/percent", version: "v0.2.1", sum: "h1:5gssi8Nqo8QU/r2pynCm+hBQHpkB/uNK7BJCFogWdzs=" }, Module { path: "github.com/pelletier/go-toml", version: "v1.8.0", sum: "h1:Keo9qb7iRJs2voHvunFtuuYFsbWeOBh8/P9v/kVMFtw=" }, Module { path: "github.com/pkg/errors", version: "v0.9.1", sum: "h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=" }, Module { path: "github.com/pmezard/go-difflib", version: "v1.0.0", sum: "h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=" }, Module { path: "github.com/prometheus/client_golang", version: "v1.8.0", sum: "h1:zvJNkoCFAnYFNC24FV8nW4JdRJ3GIFcLbg65lL/JDcw=" }, Module { path: "github.com/prometheus/client_model", version: "v0.2.0", sum: "h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=" }, Module { path: "github.com/prometheus/common", version: "v0.15.0", sum: "h1:4fgOnadei3EZvgRwxJ7RMpG1k1pOZth5Pc13tyspaKM=" }, Module { path: "github.com/prometheus/procfs", version: "v0.2.0", sum: "h1:wH4vA7pcjKuZzjF7lM8awk4fnuJO6idemZXoKnULUx4=" }, Module { path: "github.com/rakyll/statik", version: "v0.1.7", sum: "h1:OF3QCZUuyPxuGEP7B4ypUa7sB/iHtqOTDYZXGM8KOdQ=" }, Module { path: "github.com/rcrowley/go-metrics", version: "v0.0.0-20200313005456-10cdbea86bc0", sum: "h1:MkV+77GLUNo5oJ0jf870itWm3D0Sjh7+Za9gazKc5LQ=" }, Module { path: "github.com/regen-network/cosmos-proto", version: "v0.3.1", sum: "h1:rV7iM4SSFAagvy8RiyhiACbWEGotmqzywPxOvwMdxcg=" }, Module { path: "github.com/rs/cors", version: "v1.7.0", sum: "h1:+88SsELBHx5r+hZ8TCkggzSstaWNbDvThkVK8H6f9ik=" }, Module { path: "github.com/rs/zerolog", version: "v1.20.0", sum: "h1:38k9hgtUBdxFwE34yS8rTHmHBa4eN16E4DJlv177LNs=" }, Module { path: "github.com/spf13/afero", version: "v1.3.4", sum: "h1:8q6vk3hthlpb2SouZcnBVKboxWQWMDNF38bwholZrJc=" }, Module { path: "github.com/spf13/cast", version: "v1.3.1", sum: "h1:nFm6S0SMdyzrzcmThSipiEubIDy8WEXKNZ0UOgiRpng=" }, Module { path: "github.com/spf13/cobra", version: "v1.1.3", sum: "h1:xghbfqPkxzxP3C/f3n5DdpAbdKLj4ZE4BWQI362l53M=" }, Module { path: "github.com/spf13/jwalterweatherman", version: "v1.1.0", sum: "h1:ue6voC5bR5F8YxI5S67j9i582FU4Qvo2bmqnqMYADFk=" }, Module { path: "github.com/spf13/pflag", version: "v1.0.5", sum: "h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=" }, Module { path: "github.com/spf13/viper", version: "v1.7.1", sum: "h1:pM5oEahlgWv/WnHXpgbKz7iLIxRf65tye2Ci+XFK5sk=" }, Module { path: "github.com/stretchr/testify", version: "v1.7.0", sum: "h1:nwc3DEeHmmLAfoZucVR881uASk0Mfjw8xYJ99tb5CcY=" }, Module { path: "github.com/subosito/gotenv", version: "v1.2.0", sum: "h1:Slr1R9HxAlEKefgq5jn9U+DnETlIUa6HfgEzj0g5d7s=" }, Module { path: "github.com/syndtr/goleveldb", version: "v1.0.1-0.20200815110645-5c35d600f0ca", sum: "h1:Ld/zXl5t4+D69SiV4JoN7kkfvJdOWlPpfxrzxpLMoUk=" }, Module { path: "github.com/tendermint/btcd", version: "v0.1.1", sum: "h1:0VcxPfflS2zZ3RiOAHkBiFUcPvbtRj5O7zHmcJWHV7s=" }, Module { path: "github.com/tendermint/crypto", version: "v0.0.0-20191022145703-50d29ede1e15", sum: "h1:hqAk8riJvK4RMWx1aInLzndwxKalgi5rTqgfXxOxbEI=" }, Module { path: "github.com/tendermint/go-amino", version: "v0.16.0", sum: "h1:GyhmgQKvqF82e2oZeuMSp9JTN0N09emoSZlb2lyGa2E=" }, Module { path: "github.com/tendermint/tendermint", version: "v0.34.9", sum: "h1:9P2MXDEPOcPW0NBcHQ/HDSfvczZm+q5nUUw7AZ6f1Vc=" }, Module { path: "github.com/tendermint/tm-db", version: "v0.6.4", sum: "h1:3N2jlnYQkXNQclQwd/eKV/NzlqPlfK21cpRRIx80XXQ=" }, Module { path: "github.com/zondax/hid", version: "v0.9.0", sum: "h1:eiT3P6vNxAEVxXMw66eZUAAnU2zD33JBkfG/EnfAKl8=" }, Module { path: "golang.org/x/crypto", version: "v0.0.0-20201221181555-eec23a3978ad", sum: "h1:DN0cp81fZ3njFcrLCytUHRSUkqBjfTo4Tx9RJTWs0EY=" }, Module { path: "golang.org/x/net", version: "v0.0.0-20201021035429-f5854403a974", sum: "h1:IX6qOQeG5uLjB/hjjwjedwfjND0hgjPMMyO1RoIXQNI=" }, Module { path: "golang.org/x/sys", version: "v0.0.0-20201015000850-e3ed0017c211", sum: "h1:9UQO31fZ+0aKQOFldThf7BKPMJTiBfWycGh/u3UoO88=" }, Module { path: "golang.org/x/term", version: "v0.0.0-20201117132131-f5c789dd3221", sum: "h1:/ZHdbVpdR/jk3g30/d4yUL0JU9kksj8+F/bnQUVLGDM=" }, Module { path: "golang.org/x/text", version: "v0.3.3", sum: "h1:cokOdA+Jmi5PJGXLlLllQSgYigAEfHXJAERHVMaCc2k=" }, Module { path: "google.golang.org/genproto", version: "v0.0.0-20210114201628-6edceaf6022f", sum: "h1:izedQ6yVIc5mZsRuXzmSreCOlzI0lCU1HpG8yEdMiKw=" }, Module { path: "google.golang.org/grpc", version: "v1.35.0", sum: "" }, Module { path: "google.golang.org/protobuf", version: "v1.25.0", sum: "h1:Ejskq+SyPohKW+1uil0JJMtmHCgJPJ/qWTxr8qp+R4c=" }, Module { path: "gopkg.in/ini.v1", version: "v1.51.0", sum: "h1:AQvPpx3LzTDM0AjnIRlVFwFFGC+npRopjZxLJj6gdno=" }, Module { path: "gopkg.in/yaml.v2", version: "v2.4.0", sum: "h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=" }, Module { path: "gopkg.in/yaml.v3", version: "v3.0.0-20200313102051-9f266ea9e77c", sum: "h1:dUUwHk2QECo/6vqA44rthZ8ie2QXMNeKRTHCNY2nXvo=" }], cosmos_sdk_version: "" }
```

**Review by soareschen — APPROVED** [review]

**Comment by JonathanLorimer** [comment]
@soareschen where is `debug.ReadBuildInfo()` called in gaia? I grepped the project and couldn't find it. I have an idea, but need to test.

**Comment by soareschen** [comment]
[Here](https://github.com/cosmos/cosmos-sdk/blob/v0.44.3/version/version.go#L89-L90)

**Comment by JonathanLorimer** [comment]
Oh, I see, its called in a dependency, I am not sure if gomod2nix builds dependencies or just provides the source in the vendors dir...

**Pull request merged**
