### PR TITLE
Cleanup syncGoModules, update gaia6

### PR DESCRIPTION
**Pull request by romac**

### CODE REVIEW

**Comment by romac** [comment]
Note: I wasn't able to test this locally, likely because I have no idea what I am doing

```
$ nix run '.#gaia6'
error: builder for '/nix/store/hya6p2gzxn6fpfgb1bq0nkbls82l6m8i-gaia-v6.0.0-rc2.drv' failed with exit code 1;
       last 10 log lines:
       > patching sources
       > configuring
       > building
       > Building subPackage ./app
       > app/app.go:102:2: cannot find package "." in:
       > 	/private/tmp/nix-shell.U2526p/nix-build-gaia-v6.0.0-rc2.drv-0/source/vendor/github.com/strangelove-ventures/packet-forward-middleware/router
       > app/app.go:103:2: cannot find package "." in:
       > 	/private/tmp/nix-shell.U2526p/nix-build-gaia-v6.0.0-rc2.drv-0/source/vendor/github.com/strangelove-ventures/packet-forward-middleware/router/keeper
       > app/app.go:104:2: cannot find package "." in:
       > 	/private/tmp/nix-shell.U2526p/nix-build-gaia-v6.0.0-rc2.drv-0/source/vendor/github.com/strangelove-ventures/packet-forward-middleware/router/types
       For full logs, run 'nix log /nix/store/hya6p2gzxn6fpfgb1bq0nkbls82l6m8i-gaia-v6.0.0-rc2.drv'.
```

**Comment by romac** [comment]
Oh, I just saw that Gaia v6.0.0-rc3 is out: https://github.com/cosmos/gaia/releases/tag/v6.0.0-rc3

**Comment by JonathanLorimer** [comment]
@romac I definitely have bumped into this before. I am taking a look.

**Comment by JonathanLorimer** [comment]
OMG, I'm so sorry, my `syncGoModules` check had a bug. I was using `msum` instead of `mconcat` and getting the wrong monoid instance for `All`. Anyways, you didn't run `syncGoModules` to get updated gomod2nix dependencies. You couldn't have known to do this, and it should have failed `nix flake check` / ci because of this with a message to run that command, but my script was bugged.

**Comment by JonathanLorimer** [comment]
@romac I hope you don't mind, but I took the liberty of fixing the `sync.hs` and updating gaia6 to rc3. Everything is working now!

**Pull request merged**
