### PR TITLE
feat: cw limit size according default cosmos host

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by dzmitry-lahoda** [comment]
cc @JonathanLorimer

**Review by JonathanLorimer — APPROVED** [review]

**Comment by JonathanLorimer** [comment]
@dzmitry-lahoda looks great, feel free to merge whenever

**Review by JonathanLorimer — APPROVED** [review]

**Comment by JonathanLorimer** [comment]
CI is going to keep failing until this merges https://github.com/informalsystems/cosmos.nix/pull/192

I accidentally broke the CI workflow for PR's from forks.

**Review by JonathanLorimer — APPROVED** [review]

**Comment by JonathanLorimer** [comment]
@dzmitry-lahoda feel free to merge whenever

**Comment by dzmitry-lahoda** [comment]
hello, merge button is not available for me

**Pull request merged**
