### PR TITLE
Package Simd

### PR DESCRIPTION
**Pull request by JonathanLorimer**
Closes https://github.com/informalsystems/cosmos.nix/issues/12

### CODE REVIEW

**Comment by JonathanLorimer** [comment]
Closes https://github.com/informalsystems/cosmos.nix/issues/12

**Comment by soareschen** [comment]
I can run `nix run .#simd` but not `nix build .#simd`. It seems inconvenient to me that Nix flakes allows different hierarchy of packages for the subcommands `nix build` and `nix run`. I like the ability of building Nix packages without having to run them.

Perhaps we should create a helper function to auto generate the `apps` attribute from the `packages` attribute in a separate PR.

**Comment by JonathanLorimer** [comment]
That's a fair criticism of flakes. In this particular case I provided a different package name than the app name because the go module that is being built is actually the `cosmos-sdk`, it just so happens that the only executable result of building `cosmos-sdk` is `simd`. I could change the derivation I call [here](https://github.com/informalsystems/cosmos.nix/pull/11/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R114-R117) to better reflect that the intent is building `simd` by calling it `simd`

**Comment by JonathanLorimer** [comment]
I am going to merge this to keep things moving forward. If you want to discuss divergences between packages and applications, we can create an issue and discuss!

**Pull request merged**
