### PR TITLE
up osmosis and centauri, added beaker, nix fmt

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by romac** [comment]
Here's the formater used on CI: https://github.com/kamadorueda/alejandra

**Comment by romac** [comment]
I wonder why the tests are not being run, any idea?

**Comment by dzmitry-lahoda** [comment]
pr from fork is not same event as pr from repo

**Comment by dzmitry-lahoda** [comment]
up @romac

**Comment by romac** [comment]
@dzmitry-lahoda Can you please enable edits from maintainers?

**Comment by romac** [comment]
All good, thanks 🙏

**Pull request merged**
