### PR TITLE
Add `ibc-go-sdk-50-simapp`

### PR DESCRIPTION
**Pull request by romac**
Not for merge, only testing for now.

Had to update the flake inputs to get Go 1.20 final instead of pre-release, but had to remove old packages whose source can't be found anymore for it to work.

### CODE REVIEW

**Comment by romac** [comment]
@JonathanLorimer Any idea what might be causing this error? Haven't been able to reproduce it outside of Nix, whether on macOS or Linux...

```
       > Building subPackage ./modules/apps/29-fee/client/cli
       > Building subPackage ./modules/apps/29-fee/keeper
       > Building subPackage ./modules/apps/29-fee/types
       > Building subPackage ./modules/apps/transfer
       > Building subPackage ./modules/apps/transfer/client/cli
       > Building subPackage ./modules/apps/transfer/keeper
       > Building subPackage ./modules/apps/transfer/simulation
       > Building subPackage ./modules/apps/transfer/types
       > Building subPackage ./modules/capability
       > main module (github.com/cosmos/ibc-go/v7) does not contain package github.com/cosmos/ibc-go/v7/modules/capability
```

**Comment by JonathanLorimer** [comment]
@romac 
https://github.com/cosmos/ibc-go/tree/v1.0.0-rc3/modules (which the top-level go mod is pointing to) does not contain `/modules/capability`
but that is what is being required here: https://github.com/cosmos/ibc-go/blob/upgrade-sdk-v0.50-alpha1/go.mod#L24
I have no idea how this ever worked?

**Comment by JonathanLorimer** [comment]
This is probably my lack of understanding of the go module system, but maybe nix things that require is pointing to the link I posted, but its actually meant to resolve to this https://github.com/cosmos/ibc-go/tree/modules/capability/v1.0.0-rc3/modules

**Comment by JonathanLorimer** [comment]
forgive my ignorance, but if you are actually supposed to split tags like that in the go.mod file and its supposed to map to `modules/capability/v1.0.0-rc3` that seems a little crazy to me.

**Comment by crodriguezvega** [comment]
Thanks for the investigation on this issue, @JonathanLorimer. It's very weird: ibc-go imports the capability module and the capability module has its own go.mod so there shouldn't be any `github.com/cosmos/ibc-go/v7/modules/capability`, but instead `github.com/cosmos/ibc-go/modules/capability` (v7 applies only to ibc-go). I don't understand why it's trying to look for `github.com/cosmos/ibc-go/v7/modules/capability`...

**Comment by romac** [comment]
Superseded by https://github.com/informalsystems/cosmos.nix/pull/160 for IBC Go v8-alpha.1.

Unfortunately the build still fails with a similar error: https://github.com/informalsystems/cosmos.nix/pull/160#issuecomment-1710075743

**Comment by soareschen** [comment]
Subdirectories that contain their own `go.mod` have to be manually excluded from the Nix package definition using `excludedPackages`. Otherwise Nix would assume that all Go code in the source belong to the same Go module, hence why the build failed.

I think this is more of an issue of code organization in Go projects like ibc-go. Ideally, each Go module should be placed in their own subdirectory within the project, instead of nesting one module within the subdirectory of another. Doing so would also make it easier for external users to discover what Go modules are offered by a Go project by simply scanning a root directory.

**Pull request closed without merging**
